<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PersonalInformation;
use App\Enums\Scholarship;
use App\Enums\BloodType;
use App\Enums\Religion;
use App\Enums\ShirtSize;

class PersonalInformationSeeder extends Seeder
{
    public function run(): void
    {
        $personal_information = [
            [
                'id' => 1,
                'user_id' => 5,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-01-22',
                'weight' => 65,
                'height' => 165,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::AB,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '1/1',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 2,
                'user_id' => 6,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-08-24',
                'weight' => 62,
                'height' => 170,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '2/2',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 3,
                'user_id' => 7,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-06-13',
                'weight' => 46,
                'height' => 167,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '3/3',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 4,
                'user_id' => 8,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-11-20',
                'weight' => 57,
                'height' => 169,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '4/4',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 5,
                'user_id' => 9,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-05-26',
                'weight' => 64,
                'height' => 170,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '5/5',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 6,
                'user_id' => 10,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-05-03',
                'weight' => 67,
                'height' => 175,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '6/6',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 7,
                'user_id' => 11,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-08-06',
                'weight' => 52,
                'height' => 174,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '7/7',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 8,
                'user_id' => 12,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-07-13',
                'weight' => 67,
                'height' => 173,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '8/8',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 9,
                'user_id' => 13,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-10-20',
                'weight' => 48,
                'height' => 174,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '9/9',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 10,
                'user_id' => 14,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-10-15',
                'weight' => 53,
                'height' => 169,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '10/10',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 11,
                'user_id' => 15,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-03-11',
                'weight' => 59,
                'height' => 164,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '11/11',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 12,
                'user_id' => 16,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-06-01',
                'weight' => 50,
                'height' => 176,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '12/12',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 13,
                'user_id' => 17,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-10-04',
                'weight' => 61,
                'height' => 179,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '13/13',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 14,
                'user_id' => 18,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-02-16',
                'weight' => 47,
                'height' => 173,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::AB,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '14/14',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 15,
                'user_id' => 19,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-01-14',
                'weight' => 54,
                'height' => 165,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::AB,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '15/15',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 16,
                'user_id' => 20,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-02-17',
                'weight' => 57,
                'height' => 176,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '16/16',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 17,
                'user_id' => 21,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-04-14',
                'weight' => 60,
                'height' => 178,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '17/17',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 18,
                'user_id' => 22,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-05-20',
                'weight' => 65,
                'height' => 167,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '18/18',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 19,
                'user_id' => 23,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-02-26',
                'weight' => 68,
                'height' => 172,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '19/19',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 20,
                'user_id' => 24,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-09-19',
                'weight' => 60,
                'height' => 178,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '20/20',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'user_id' => 25,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-10-22',
                'weight' => 66,
                'height' => 164,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::AB,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '21/21',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 22,
                'user_id' => 26,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-06-04',
                'weight' => 58,
                'height' => 178,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '22/22',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 23,
                'user_id' => 27,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-03-02',
                'weight' => 55,
                'height' => 166,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '23/23',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 24,
                'user_id' => 28,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-11-24',
                'weight' => 67,
                'height' => 173,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '24/24',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 25,
                'user_id' => 29,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-02-03',
                'weight' => 68,
                'height' => 163,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '25/25',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 26,
                'user_id' => 30,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-10-04',
                'weight' => 65,
                'height' => 160,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '26/26',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 27,
                'user_id' => 31,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-04-20',
                'weight' => 46,
                'height' => 179,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '27/27',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 28,
                'user_id' => 32,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-06-23',
                'weight' => 56,
                'height' => 172,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '28/28',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 29,
                'user_id' => 33,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-06-27',
                'weight' => 48,
                'height' => 164,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::AB,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '29/29',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 30,
                'user_id' => 34,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-07-22',
                'weight' => 53,
                'height' => 172,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '30/30',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 31,
                'user_id' => 35,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-08-26',
                'weight' => 57,
                'height' => 166,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::XL,
                'interest' => null,
                'address' => '31/31',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 32,
                'user_id' => 36,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-07-04',
                'weight' => 53,
                'height' => 178,
                'email' => null,
                'scholarship' => Scholarship::NO,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '32/32',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 33,
                'user_id' => 37,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-08-16',
                'weight' => 65,
                'height' => 176,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::AB,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::L,
                'interest' => null,
                'address' => '33/33',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 34,
                'user_id' => 38,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-11-26',
                'weight' => 66,
                'height' => 176,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::A,
                'religion' => Religion::ISLAM,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '34/34',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 35,
                'user_id' => 39,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-05-17',
                'weight' => 54,
                'height' => 168,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::B,
                'religion' => Religion::CHRISTIANITY,
                'shirt_size' => ShirtSize::S,
                'interest' => null,
                'address' => '35/35',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 36,
                'user_id' => 40,
                'nationality' => '764',
                'ethnicity' => '764',
                'birth_date' => '2000-06-19',
                'weight' => 49,
                'height' => 179,
                'email' => null,
                'scholarship' => Scholarship::YES,
                'disability' => null,
                'blood_type' => BloodType::O,
                'religion' => Religion::BUDDHISM,
                'shirt_size' => ShirtSize::M,
                'interest' => null,
                'address' => '36/36',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        PersonalInformation::insert($personal_information);
    }
}
