<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Enums\Prefix;
use App\Enums\Role;
use App\Enums\Status;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $password = 'P@ssw0rd';
        $users = [
            [
                'id' => 1,
                'username' => '016340664011-7',
                'password' => Hash::make($password),
                'first_name_th' => 'สมชาย',
                'last_name_th' => 'พงษ์ทอง',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Somchai',
                'last_name_en' => 'Phongthong',
                'rmutto_email' => 'somchai.pho@rmutto.ac.th',
                'tel' => '0863112728',
                'role' => Role::ADMIN,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 2,
                'username' => '016340664012-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ณัฐพงศ์',
                'last_name_th' => 'เจริญ',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Nattapong',
                'last_name_en' => 'Charoen',
                'rmutto_email' => 'nattapong.cha@rmutto.ac.th',
                'tel' => '0883999200',
                'role' => Role::TEACHER,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 3,
                'username' => '016340664013-7',
                'password' => Hash::make($password),
                'first_name_th' => 'พัชร',
                'last_name_th' => 'นพรัตน์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Patchara',
                'last_name_en' => 'Nopparat',
                'rmutto_email' => 'patchara.nop@rmutto.ac.th',
                'tel' => '0825377709',
                'role' => Role::TEACHER,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 4,
                'username' => '016340664014-7',
                'password' => Hash::make($password),
                'first_name_th' => 'กัญญา',
                'last_name_th' => 'รุ่งวงศ์',
                'prefix' => Prefix::MRS,
                'first_name_en' => 'Kanya',
                'last_name_en' => 'Rungwong',
                'rmutto_email' => 'kanya.run@rmutto.ac.th',
                'tel' => '0811066632',
                'role' => Role::TEACHER,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 5,
                'username' => '016340664015-7',
                'password' => Hash::make($password),
                'first_name_th' => 'อธิษเศรษฐ์',
                'last_name_th' => 'จันทจำรัสปัญญา',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Athiset',
                'last_name_en' => 'Chantachumratpanya',
                'rmutto_email' => 'athiset.cha@rmutto.ac.th',
                'tel' => '0925371266',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 6,
                'username' => '016340664016-7',
                'password' => Hash::make($password),
                'first_name_th' => 'อภิญญา',
                'last_name_th' => 'พงษ์ทัน',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Apinya',
                'last_name_en' => 'Pongthan',
                'rmutto_email' => 'apinya.pon@rmutto.ac.th',
                'tel' => '0879692808',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 7,
                'username' => '016340664017-7',
                'password' => Hash::make($password),
                'first_name_th' => 'รัตนพร',
                'last_name_th' => 'บุญรักษ์',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Rattanaporn',
                'last_name_en' => 'Boonrak',
                'rmutto_email' => 'rattanaporn.boo@rmutto.ac.th',
                'tel' => '0888963499',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 8,
                'username' => '016340664018-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ปัญญา',
                'last_name_th' => 'จัน',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Panya',
                'last_name_en' => 'Jan',
                'rmutto_email' => 'panya.jan@rmutto.ac.th',
                'tel' => '0808657542',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 9,
                'username' => '016340664019-7',
                'password' => Hash::make($password),
                'first_name_th' => 'กิตติศักดิ์',
                'last_name_th' => 'พันธ์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Kittisak',
                'last_name_en' => 'Phan',
                'rmutto_email' => 'kittisak.pha@rmutto.ac.th',
                'tel' => '0847605276',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 10,
                'username' => '016340664020-7',
                'password' => Hash::make($password),
                'first_name_th' => 'นุชรี',
                'last_name_th' => 'เลิศ',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Nucharee',
                'last_name_en' => 'Lert',
                'rmutto_email' => 'nucharee.ler@rmutto.ac.th',
                'tel' => '0844104115',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 11,
                'username' => '016340664021-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ประกฤษ',
                'last_name_th' => 'เจริญ',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Prakrit',
                'last_name_en' => 'Jaroen',
                'rmutto_email' => 'prakrit.jar@rmutto.ac.th',
                'tel' => '0831248779',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 12,
                'username' => '016340664022-7',
                'password' => Hash::make($password),
                'first_name_th' => 'บุษราคัม',
                'last_name_th' => 'กิตติศักดิ์',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Busarakham',
                'last_name_en' => 'Kittisak',
                'rmutto_email' => 'busarakham.kit@rmutto.ac.th',
                'tel' => '0805927617',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 13,
                'username' => '016340664023-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ประภาพร',
                'last_name_th' => 'โพธิ์ทอง',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Prapaporn',
                'last_name_en' => 'Phothong',
                'rmutto_email' => 'prapaporn.pho@rmutto.ac.th',
                'tel' => '0820685431',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 14,
                'username' => '016340664024-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ฉัตรชัย',
                'last_name_th' => 'วงศ์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Chatchai',
                'last_name_en' => 'Wong',
                'rmutto_email' => 'chatchai.won@rmutto.ac.th',
                'tel' => '0877246470',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 15,
                'username' => '016340664025-7',
                'password' => Hash::make($password),
                'first_name_th' => 'สุริยา',
                'last_name_th' => 'คำบุญ',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Suriya',
                'last_name_en' => 'Khamboon',
                'rmutto_email' => 'suriya.kha@rmutto.ac.th',
                'tel' => '0847181939',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 16,
                'username' => '016340664026-7',
                'password' => Hash::make($password),
                'first_name_th' => 'วิยะดา',
                'last_name_th' => 'สิทธิชัย',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Viyada',
                'last_name_en' => 'Sittichai',
                'rmutto_email' => 'viyada.sit@rmutto.ac.th',
                'tel' => '0850020096',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 17,
                'username' => '016340664027-7',
                'password' => Hash::make($password),
                'first_name_th' => 'นิรันดร์',
                'last_name_th' => 'จิตต์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Niran',
                'last_name_en' => 'Jit',
                'rmutto_email' => 'niran.jit@rmutto.ac.th',
                'tel' => '0898462759',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 18,
                'username' => '016340664028-7',
                'password' => Hash::make($password),
                'first_name_th' => 'สิริพร',
                'last_name_th' => 'กมล',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Siriporn',
                'last_name_en' => 'Kamon',
                'rmutto_email' => 'siriporn.kam@rmutto.ac.th',
                'tel' => '0825829914',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 19,
                'username' => '016340664029-7',
                'password' => Hash::make($password),
                'first_name_th' => 'สมพล',
                'last_name_th' => 'นวล',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Sompol',
                'last_name_en' => 'Nuan',
                'rmutto_email' => 'sompol.nua@rmutto.ac.th',
                'tel' => '0803700156',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 20,
                'username' => '016340664030-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ธิดา',
                'last_name_th' => 'จิตร',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Thida',
                'last_name_en' => 'Chit',
                'rmutto_email' => 'thida.chi@rmutto.ac.th',
                'tel' => '0806387751',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'username' => '016340664031-7',
                'password' => Hash::make($password),
                'first_name_th' => 'กิตติพงศ์',
                'last_name_th' => 'นรินทร์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Kittipong',
                'last_name_en' => 'Narin',
                'rmutto_email' => 'kittipong.nar@rmutto.ac.th',
                'tel' => '0812338420',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 22,
                'username' => '016340664032-7',
                'password' => Hash::make($password),
                'first_name_th' => 'เพ็ญพักตร์',
                'last_name_th' => 'เพทราจันทร์',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Penpak',
                'last_name_en' => 'Phetrachan',
                'rmutto_email' => 'penpak.phe@rmutto.ac.th',
                'tel' => '0846401977',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 23,
                'username' => '016340664033-7',
                'password' => Hash::make($password),
                'first_name_th' => 'นริศรา',
                'last_name_th' => 'พงศ์',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Narisara',
                'last_name_en' => 'Phong',
                'rmutto_email' => 'narisara.pho@rmutto.ac.th',
                'tel' => '0899221132',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 24,
                'username' => '016340664034-7',
                'password' => Hash::make($password),
                'first_name_th' => 'กฤษฎา',
                'last_name_th' => 'บุญส่ง',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Kritsada',
                'last_name_en' => 'Boonsong',
                'rmutto_email' => 'kritsada.boo@rmutto.ac.th',
                'tel' => '0819244360',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 25,
                'username' => '016340664035-7',
                'password' => Hash::make($password),
                'first_name_th' => 'วัลลภ',
                'last_name_th' => 'กิตติพงศ์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Wanlop',
                'last_name_en' => 'Kittiphong',
                'rmutto_email' => 'wanlop.kit@rmutto.ac.th',
                'tel' => '0886055253',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 26,
                'username' => '016340664036-7',
                'password' => Hash::make($password),
                'first_name_th' => 'รัชนีย์',
                'last_name_th' => 'คำเลิศ',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Rachanee',
                'last_name_en' => 'Khamloet',
                'rmutto_email' => 'rachanee.kha@rmutto.ac.th',
                'tel' => '0864516284',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 27,
                'username' => '016340664037-7',
                'password' => Hash::make($password),
                'first_name_th' => 'พรชัย',
                'last_name_th' => 'บุญชู',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Phonchai',
                'last_name_en' => 'Boonchoo',
                'rmutto_email' => 'phonchai.boo@rmutto.ac.th',
                'tel' => '0894718884',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 28,
                'username' => '016340664038-7',
                'password' => Hash::make($password),
                'first_name_th' => 'กัญญา',
                'last_name_th' => 'มณี',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Kanya',
                'last_name_en' => 'Manee',
                'rmutto_email' => 'kanya.man@rmutto.ac.th',
                'tel' => '0863222984',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 29,
                'username' => '016340664039-7',
                'password' => Hash::make($password),
                'first_name_th' => 'รัศมี',
                'last_name_th' => 'จิตรพงศ์',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Rassamee',
                'last_name_en' => 'Jitphong',
                'rmutto_email' => 'rassamee.jit@rmutto.ac.th',
                'tel' => '0882737116',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 30,
                'username' => '016340664040-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ธาดา',
                'last_name_th' => 'กนิษฐ์',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Tada',
                'last_name_en' => 'Kanit',
                'rmutto_email' => 'tada.kan@rmutto.ac.th',
                'tel' => '0813371483',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 31,
                'username' => '016340664041-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ลัดดาวัลย์',
                'last_name_th' => 'ชัย',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Laddawan',
                'last_name_en' => 'Chai',
                'rmutto_email' => 'laddawan.cha@rmutto.ac.th',
                'tel' => '0820924985',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 32,
                'username' => '016340664042-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ชิตพัส',
                'last_name_th' => 'ณัชชา',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Chitpas',
                'last_name_en' => 'Natcha',
                'rmutto_email' => 'chitpas.nat@rmutto.ac.th',
                'tel' => '0899796235',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 33,
                'username' => '016340664043-7',
                'password' => Hash::make($password),
                'first_name_th' => 'กนกพล',
                'last_name_th' => 'พงษ์น้ำ',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Kanokpon',
                'last_name_en' => 'Phongnam',
                'rmutto_email' => 'kanokpon.pho@rmutto.ac.th',
                'tel' => '0805403121',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 34,
                'username' => '016340664044-7',
                'password' => Hash::make($password),
                'first_name_th' => 'วรนุช',
                'last_name_th' => 'นาฏศิลป์',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Woranuch',
                'last_name_en' => 'Nart',
                'rmutto_email' => 'woranuch.nar@rmutto.ac.th',
                'tel' => '0834387700',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 35,
                'username' => '016340664045-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ประวิทย์',
                'last_name_th' => 'ศรีสุวรรณ',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Prawit',
                'last_name_en' => 'Srisuwan',
                'rmutto_email' => 'prawit.sri@rmutto.ac.th',
                'tel' => '0865565645',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 36,
                'username' => '016340664046-7',
                'password' => Hash::make($password),
                'first_name_th' => 'สิริวรรณ',
                'last_name_th' => 'วงศ์สกุล',
                'prefix' => Prefix::MISS,
                'first_name_en' => 'Siriwan',
                'last_name_en' => 'Wongsakul',
                'rmutto_email' => 'siriwan.won@rmutto.ac.th',
                'tel' => '0855903717',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 37,
                'username' => '016340664047-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ศุภชัย',
                'last_name_th' => 'รุ่งระ',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Supachai',
                'last_name_en' => 'Rungra',
                'rmutto_email' => 'supachai.run@rmutto.ac.th',
                'tel' => '0895703577',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 38,
                'username' => '016340664048-7',
                'password' => Hash::make($password),
                'first_name_th' => 'ภัทรพล',
                'last_name_th' => 'แจ่มจรัส',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Phattharapon',
                'last_name_en' => 'Jamcharat',
                'rmutto_email' => 'phattharapon.jam@rmutto.ac.th',
                'tel' => '0876771759',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 39,
                'username' => '016340664049-7',
                'password' => Hash::make($password),
                'first_name_th' => 'จารุวัฒน์',
                'last_name_th' => 'หอมนิ่ม',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Jaruwat',
                'last_name_en' => 'Homnim',
                'rmutto_email' => 'jaruwat.hom@rmutto.ac.th',
                'tel' => '0891175555',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 40,
                'username' => '016340664050-7',
                'password' => Hash::make($password),
                'first_name_th' => 'อภิรักษ์',
                'last_name_th' => 'กลิ่นหอม',
                'prefix' => Prefix::MR,
                'first_name_en' => 'Apirak',
                'last_name_en' => 'Grinhom',
                'rmutto_email' => 'apirak.gri@rmutto.ac.th',
                'tel' => '0844086026',
                'role' => Role::STUDENT,
                'status' => Status::ENABLE,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        User::insert($users);
    }
}
